### ISSUE TITLE
Move to Netlify

### ISSUE THREAD

**Issue by lukekarrys** [andyet/face.camp#99]
- [x] Update `face.camp` and `www.face.camp` DNS records
- [x] Verify DNS
- [x] Delete zeit `face.camp` deployment
- [x] Test Slack auth inside Netlify functions
- [x] Update auth url to `face.camp/.netlify/functions`
- [x] Delete `auth.face.camp` DNS record
- [x] Delete `auth.face.camp` k8s deployment
- [x] Figure out and document local dev with `netlify-lambda serve`
- [x] <del>Figure out local https testing</del> https://github.com/andyet/face.camp/issues/111
- [x] <del>Figure out Slack `redirect_uri` issue when using localhost and/or ngrok</del> https://github.com/andyet/face.camp/issues/109
- [x] <del>Test netilfy functions</del> https://github.com/andyet/face.camp/issues/110
